name:                assignment1
version:             0.1.0.0

dependencies:
- base

library:
  source-dirs: src
  other-modules: []
  dependencies:
  - array
  build-tools:
  - alex
  - happy

executables:
  assignment1-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - assignment1
    other-modules: []

tests:
  assignment1-test:
    main:                doctest-driver.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - assignment1
    - doctest
    - doctest-discover
    other-modules: []
