name:                tutorial1
version:             0.1.0.0

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  other-modules: []

executables:
  tutorial1-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tutorial1
    other-modules: []

tests:
  tutorial1-test:
    main:                doctest-driver.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tutorial1
    - doctest
    - doctest-discover
    other-modules: []
